ECommerceWeb/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ECommerceWeb.Controllers
{
    public class SliderController : Controller
    {
        dbEcommerceEntities _context;
        public SliderController()
        {
            _context=new dbEcommerceEntities();
        }
        public ActionResult SlidesList()
        {
            var slides = _context.Tble_SlideImage.ToList();
            return View(slides);
        }
        public ActionResult Details(int? id)
        {
            var slide = _context.Tble_SlideImage.Find(id);
            return View(slide);
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase file,Tble_SlideImage slides)
        {
            if(file!=null)
            {
                string filename = Path.GetFileName(file.FileName);
                string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                string extension = Path.GetExtension(file.FileName);
                string path = Path.Combine(Server.MapPath("~/SliderImg/"), _filename);
                slides.slideImage = "~/SliderImg/" + _filename;
                if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                {
                    if (file.ContentLength <= 1000000)
                    {
                        _context.Tble_SlideImage.Add(slides);
                        if (_context.SaveChanges() > 0)
                        {
                            file.SaveAs(path);
                            ModelState.Clear();
                        }
                    }
                    else
                    {
                        ViewBag.msg = "File size must be Equal or greater than 1MB";
                    }
                }
                else
                {
                    ViewBag.msg = "Invalid File Type";
                }
            }
            else
            {
                ViewBag.msg = "File not Uploaded";
                return View("Create");
            }
            
            return RedirectToAction("SlidesList");
        }
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var slide = _context.Tble_SlideImage.Find(id);

            Session["imgPath"] = slide.slideImage;

            if (slide == null)
                return HttpNotFound();

            
            return View(slide);
        }

        [HttpPost]
        public ActionResult Edit(HttpPostedFileBase file, Tble_SlideImage slides)
        {
            
                if (file != null && slides.SlideId>0)
                {
                    string filename = Path.GetFileName(file.FileName);
                    string _filename = DateTime.Now.ToString("yymmssfff") + filename;
                    string extension = Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/SliderImg/"), _filename);
                    slides.slideImage = "~/SliderImg/" + _filename;
                    if (extension.ToLower() == ".jpg" || extension.ToLower() == ".jpeg" || extension.ToLower() == ".png")
                    {
                        if (file.ContentLength <= 1000000)
                        {
                            _context.Entry(slides).State = System.Data.Entity.EntityState.Modified;

                            if (_context.SaveChanges() > 0)
                            {
                                file.SaveAs(path);
                                TempData["msg"] = "Data Updated";
                                return RedirectToAction("SlidesList");
                            }
                        }
                        else
                        {
                            ViewBag.msg = "File size must be Equal or greater than 1MB";
                        }
                    }
                    else
                    {
                        ViewBag.msg = "Invalid File Type";
                    }
                }
                else
                {
                    slides.slideImage= Session["imgPath"].ToString();
                    _context.Entry(slides).State = System.Data.Entity.EntityState.Modified;
                    if (_context.SaveChanges() > 0)
                    {
                        TempData["msg"] = "Data Updated";
                        return RedirectToAction("SlidesList");
                    }
                }
            


            return RedirectToAction("SlidesList");
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Tble_SlideImage slides = _context.Tble_SlideImage.Find(id);

            if (slides == null)
                return HttpNotFound();

            _context.Tble_SlideImage.Remove(slides);
            _context.SaveChanges();

            return RedirectToAction("SlidesList");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
                _context.Dispose();
            base.Dispose(disposing);
        }
    }
}

ECommerceWeb/Views/Slider/Create.cshtml
@model ECommerceWeb.Tble_SlideImage

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create Slider</h2>
<h4 class="text-danger">@ViewBag.msg</h4>
@using (Html.BeginForm("Create", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.SlideId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SlideId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SlideId, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.SlideTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SlideTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SlideTitle, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <br />
        <div class="col-md-6">
            <div class="form-group">
                @Html.LabelFor(model => model.slideImage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="file" id="file" style="width:100%" />
                    @Html.ValidationMessageFor(model => model.slideImage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <br />
        <div class="col-md-6">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    
                    <input type="submit" value="Save Slider" class="btn btn-primary mr-2" />
                    @Html.ActionLink("Slides List", "SlidesList", null, new { @class = "btn btn-primary mr-2" })
                </div>
            </div>
        </div>
    </div>
    <br />
}

ECommerceWeb/Views/Slider/Edit.cshtml
@model ECommerceWeb.Tble_SlideImage

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Edit Slide Images</h2>
<h4 class="text-danger">@ViewBag.msg</h4>
@using (Html.BeginForm("Edit", "Slider", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.SlideId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SlideId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SlideId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.SlideTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SlideTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SlideTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.slideImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Url.Content(Session["imgPath"].ToString())" width="100" height="70" />
                <input type="file" name="file" id="file" style="width:100%" />
                @Html.ValidationMessageFor(model => model.slideImage, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.HiddenFor(m => m.SlideId)
                <input type="submit" value="Update Slides" class="btn btn-primary mr-2" />
                @Html.ActionLink("Slides List", "SlidesList", null, new { @class = "btn btn-primary mr-2" })
            </div>
        </div>
    </div>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

ECommerceWeb/Views/Slider/SlidesList.cshtml
@model IEnumerable<ECommerceWeb.Tble_SlideImage>

@{
    ViewBag.Title = "SlidesList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Slides List</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary mr-2" })
</p>

<h4 class="text-success">@TempData["msg"]</h4>

<table class="table">
    <tr>
        <th>
            S.No
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SlideTitle)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.slideImage)
        </th>*@
        <th>Action</th>
    </tr>
    @if (Model != null)
    {
        int count = 1;
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @count
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SlideTitle)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.slideImage)
                </td>*@
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.SlideId }, new { @class = "btn btn-primary mr-2" }) |
                @*@Html.ActionLink("Details", "Details", new { id = item.SlideId }, new { @class = "btn btn-primary " })*@
                @Html.ActionLink("Delete", "Delete", new { id = item.SlideId }, new { @class = "btn btn-danger " })
            </td>
               
            </tr>
            { count = count + 1; }
        }
    }

    </table>